package p20.insitu.util

enum class TabType {
    ADDRESS_DETAILS,
    AUDIO_ANNOTATIONS,
    AUDIO_PLAYER,
    CRIME_SCENES,
    NEW_INVESTIGATION_CRIME_SCENES,
    CRIMINAL_OFFENSES,
    NEW_INVESTIGATION_CRIMINAL_OFFENSES,
    ENTITY_DETAILS,
    EVIDENCE_DATA,
    IMAGE_ANNOTATIONS,
    MAP,
    MODUS_OPERANDI,
    NOTE_ANNOTATIONS,
    PERSONS,
    VIDEO_ANNOTATIONS;

    fun isMediaTab(): Boolean {
        return this == AUDIO_ANNOTATIONS || this == IMAGE_ANNOTATIONS || this == NOTE_ANNOTATIONS || this == VIDEO_ANNOTATIONS
    }
}