package p20.insitu.model.entities.enums

enum class EntityType: EntityTypeIdentifier {
    ADDRESS,
    ADDRESS_RELATION,
    AIRCRAFT,
    AMMUNITION,
    ANNOTATION_RELATION,
    APARTMENT,
    AREA,
    AUDIO,
    AUDIT_ENTRY,
    AUTHORITY,

    BICYCLE,
    BODY_PART,
    BUILDING,

    CASH,
    CORPSE,
    COUNTERFEIT_MONEY,
    CRIME_SCENE,
    CRIME_SCENE_RELATION,
    CRIMINAL_OFFENSE,
    CRIMINAL_OFFENSE_RELATION,

    DEVICE,
    DNA_TRACE,
    DOCUMENT,
    DOOR,
    DRUG,
    DRUG_RAW_MATERIAL,

    EVENT,
    EVENT_RELATION,
    EXPLOSIVE_DEVICE,
    EXPLOSIVE_SUBSTANCE,

    FIREARM,
    FLOOR,

    GENERAL_RELATION,

    IMAGE,
    IMAGE_TAG,
    INVESTIGATION,
    INVESTIGATION_RELATION,

    LICENSE_PLATE,

    MEDICINE,
    MOTOR_VEHICLE,

    NOTE,

    PAYMENT_CARD,
    PERSON,
    PERSON_GROUP,
    PHYSICAL_TRACE,
    POINT_CLOUD,
    PORTABLE_OBJECT,

    RAIL_VEHICLE,
    RECORD,
    ROOM,

    SITE_RELATION,
    SKETCH,
    SOME_OBJECT,
    SOME_SITE,
    SOME_VEHICLE,
    SOVEREIGN_ACT,
    SOVEREIGN_ACT_RELATION,

    TOPOLOGICAL_RELATION,

    USER_SETTINGS,

    VIDEO,

    WALL,
    WATERCRAFT,
    WEAPON_OF_MASS_DESTRUCTION,
    WEAPON_PART,
    WEAPON_SYSTEM,
    WINDOW,
}